name: SonarCloud Analysis

on:
  push:
    branches:
      - main # or your default branch
  pull_request:
    branches:
      - main # or your default branch

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Cache SonarCloud dependencies
      uses: actions/cache@v3
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-${{ hashFiles('**/*.gradle*', '**/*.maven*') }}
        restore-keys: |
          ${{ runner.os }}-sonar-

    - name: Install dependencies
      run: |
        # Assuming you're using Maven or Gradle
        mvn install # or gradle build, depending on your project

    - name: Run SonarCloud analysis
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}

    - name: Upload Quality Gate status
      uses: sonarsource/sonarcloud-github-action@v2
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}
